version: '3.8'

services:
  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  bot:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=sqlite:///app.db
      - REDIS_URI=redis://redis:6379/0
      - LOG_LEVEL=INFO
      - CHECK_INTERVAL=300
      - RETRY_DELAY=60
      - MAX_RETRIES=3
      - WEBSITE_BASE_URL=${WEBSITE_BASE_URL}
      - WEBSITE_TIMEOUT=30
      - CAPTCHA_ENABLED=true
      - CAPTCHA_SOLUTION_TIMEOUT=30
      - CAPTCHA_2CAPTCHA_API_KEY=${CAPTCHA_2CAPTCHA_API_KEY}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-2captcha}
      - CHECK_RATE_LIMIT=10
      - CHECK_RATE_WINDOW=60
      - BOOK_RATE_LIMIT=5
      - BOOK_RATE_WINDOW=60
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
      - PERSON_COUNT=${PERSON_COUNT}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  celery:
    build: .
    restart: always
    depends_on:
      - redis
    command: celery -A src.tasks.celery worker --loglevel=info
    environment:
      - DATABASE_URL=sqlite:///app.db
      - REDIS_URI=redis://redis:6379/0
      - LOG_LEVEL=INFO
      - WEBSITE_BASE_URL=${WEBSITE_BASE_URL}
      - WEBSITE_TIMEOUT=30
      - CAPTCHA_ENABLED=true
      - CAPTCHA_SOLUTION_TIMEOUT=30
      - CAPTCHA_2CAPTCHA_API_KEY=${CAPTCHA_2CAPTCHA_API_KEY}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-2captcha}
      - CHECK_RATE_LIMIT=10
      - CHECK_RATE_WINDOW=60
      - BOOK_RATE_LIMIT=5
      - BOOK_RATE_WINDOW=60
      - USER_NAME=${USER_NAME}
      - USER_EMAIL=${USER_EMAIL}
      - PERSON_COUNT=${PERSON_COUNT}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

volumes:
  redis_data:

networks:
  mta_network:
    driver: bridge
