export const USE_CASE_EXECUTOR = 'USE_CASE_EXECUTOR';

export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
export const BROWSER_SERVICE = 'BROWSER_SERVICE';
export const API_SERVICE = 'API_SERVICE';
export const AI_SERVICE = 'AI_SERVICE';
export const STATE_SERVICE = 'STATE_SERVICE';
export const RATE_LIMIT_SERVICE = 'RATE_LIMIT_SERVICE';
export const RECOVERY_SERVICE = 'RECOVERY_SERVICE'; 